language: node_js
sudo: true
branches:
  only:
  - master
node_js:
- 12.18.3
before_install:
- openssl aes-256-cbc -K $encrypted_d3759803d8a1_key -iv $encrypted_d3759803d8a1_iv
  -in .travis/travis.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'NekoMio'
- git config --global user.email 'wildrage@163.com'
- npm install hexo-cli -g
- npm install @cloudbase/cli -g
addons:
  ssh_known_hosts: 
  - e.coding.net
  - nekomio.com
script:
- cd ./themes/suka
- yarn
- cd ../..
- hexo clean
- hexo g
- git clone git@github.com:nekomio/nekomio.github.io.git
- cp ./_headers ./public/
- cp ./aria2.html ./public/
- cd nekomio.github.io
- rm * -rf
- cp ../public/* ./ -rf
- git add .
- git commit -m "`date`"
- git remote add coding git@e.coding.net:WildRage/wildrage.coding.me.git
- git push coding master
- git push origin master
- tcb login --apiKeyId $qcloud_apiKeyId --apiKey $qcloud_apiKey
- tcb hosting:deploy ./public -e nekomio-1064ef
# - hexo d
